#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

// Go to the Project Settings (nut icon).
//token generated by blink
char auth[] = "e81af52a5c94452cb43ed5077957017f";
                
// Your WiFi credentials.
// Set password to "" for open networks.
char ssid[] = "hotspotname";
char pass[] = "hotspotpassword";

void setup()
{
  // Debug console
  Serial.begin(115200);

  Blynk.begin(auth, ssid, pass);
}

void loop()
{
  Blynk.run();
}

